### ISSUE TITLE
The general case for Beta distribution

### ISSUE THREAD

**Issue by SuXY15** [distributions-io/beta-random#1]
The general case seems to be wrong in this repo.

In Wikipedia [https://en.wikipedia.org/wiki/Beta_distribution](https://en.wikipedia.org/wiki/Beta_distribution), it says in **Generating beta-distributed random variates** that:

> if X and Y are independent, with \displaystyle X\sim \Gamma (\alpha ,\theta )}X \sim \Gamma(\alpha, \theta)
and {\displaystyle Y\sim \Gamma (\beta ,\theta )}Y \sim \Gamma(\beta, \theta) then

> {\displaystyle {\frac {X}{X+Y}}\sim \mathrm {B} (\alpha ,\beta ).} {\displaystyle {\frac {X}{X+Y}}\sim \mathrm {B} (\alpha ,\beta ).} So one algorithm for generating beta variates is to generate {\displaystyle {\frac {X}{X+Y}}}{\displaystyle {\frac {X}{X+Y}}}, where X is a gamma variate with parameters (α, 1) and Y is an independent gamma variate with parameters (β, 1)

**Comment by Planeshifter** [comment]
Thanks for filing this issue and pointing out the erroneous implementation of the general case.

Development has moved to https://github.com/stdlib-js/stdlib/, where the corresponding function for generating beta variates (https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/base/beta) does not suffer from this bug.

**Comment by Planeshifter** [comment]
Pushed a commit (8e83651f68e5f9a9d540f9b195fb177624a616e6) to this repo with a fix.
